package com.yiyekeji.coolschool.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LESSON_SCHEDULE".
 */
public class LessonSchedule {

    private Long id;
    private String studentNo;
    private String htmlString;

    public LessonSchedule() {
    }

    public LessonSchedule(Long id) {
        this.id = id;
    }

    public LessonSchedule(Long id, String studentNo, String htmlString) {
        this.id = id;
        this.studentNo = studentNo;
        this.htmlString = htmlString;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStudentNo() {
        return studentNo;
    }

    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getHtmlString() {
        return htmlString;
    }

    public void setHtmlString(String htmlString) {
        this.htmlString = htmlString;
    }

}
